### ISSUE TITLE
error in dr2tot data for HEI 2015

### ISSUE THREAD

**Issue by iR-start** [jamesjiadazhan/dietaryindex#136]
> FPED_PATH1 = "/2005_2006/fped_dr2tot_0506.sas7bdat"
> NUTRIENT_PATH1 = "/dietary/dr2tot_d.xpt"
> DEMO_PATH = "/demo/demo_d05_06.xpt"
> hei0506_2 <- HEI2015_NHANES_FPED(FPED_PATH1, NUTRIENT_PATH1, DEMO_PATH)
Error in `filter()`:
! Problem while computing `..1 = DR1DRSTZ == 1`.
Caused by error in `mask$eval_all_filter()`:
! object 'DR1DRSTZ' not found
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Error in `filter()`:
! Problem while computing `..1 = DR1DRSTZ == 1`.
Caused by error in `mask$eval_all_filter()`:
! object 'DR1DRSTZ' not found
---
Backtrace:
  1. dietaryindex::HEI2015_NHANES_FPED(...)
  6. dplyr:::filter.data.frame(., DR1DRSTZ == 1)
  7. dplyr:::filter_rows(.data, ..., caller_env = caller_env())
  8. dplyr:::filter_eval(dots, mask = mask, error_call = error_call)
 10. mask$eval_all_filter(dots, env_filter)
Run `rlang::last_trace()` to see the full context.

**Comment by jamesjiadazhan** [comment]
Thanks for reaching out! Sorry, HEI2015_NHANES_FPED currently only supports the first-day nutrition data. In the next update, I will make it available to use the second-day nutrition data, and perhaps merge it with the first-day data if needed.

**Comment by iR-start** [comment]
> Thanks for reaching out! Sorry, HEI2015_NHANES_FPED currently only supports the first-day nutrition data. In the next update, I will make it available to use the second-day nutrition data, and perhaps merge it with the first-day data if needed.

Thank you for your contributions in this field. Look forward to your update.

**Comment by jamesjiadazhan** [comment]
> > Thanks for reaching out! Sorry, HEI2015_NHANES_FPED currently only supports the first-day nutrition data. In the next update, I will make it available to use the second-day nutrition data, and perhaps merge it with the first-day data if needed.
> 
> Thank you for your contributions in this field. Look forward to your update.

Hi, I just updated the HEI2015_NHANES_FPED function. Now it supports day 1, day 2, or day 1 + day 2 data input. If you provide day 1 and day 2 data, the mean values will be returned. If you provide day 2 only, the day 2 values will be returned. See this example:
```
data("NHANES_20172018")
HEI2015_NHANES_FPED(FPED_PATH=NHANES_20172018$FPED, NUTRIENT_PATH=NHANES_20172018$NUTRIENT, DEMO_PATH=NHANES_20172018$DEMO, FPED_PATH2=NHANES_20172018$FPED2, NUTRIENT_PATH2=NHANES_20172018$NUTRIENT2)
```

Let me know if you have other questions. Glad to help. If you find the dietaryindex package helpful, please consider giving it a Star on GitHub. It helps recognize my work. Also, if you publish the paper, please cite the package as GitHub “dietaryindex”. The package will be written as a paper soon.

**Comment by iR-start** [comment]
> > > Thanks for reaching out! Sorry, HEI2015_NHANES_FPED currently only supports the first-day nutrition data. In the next update, I will make it available to use the second-day nutrition data, and perhaps merge it with the first-day data if needed.
> > 
> > 
> > Thank you for your contributions in this field. Look forward to your update.
> 
> Hi, I just updated the HEI2015_NHANES_FPED function. Now it supports day 1, day 2, or day 1 + day 2 data input. If you provide day 1 and day 2 data, the mean values will be returned. If you provide day 2 only, the day 2 values will be returned. See this example:
> 
> ```
> data("NHANES_20172018")
> HEI2015_NHANES_FPED(FPED_PATH=NHANES_20172018$FPED, NUTRIENT_PATH=NHANES_20172018$NUTRIENT, DEMO_PATH=NHANES_20172018$DEMO, FPED_PATH2=NHANES_20172018$FPED2, NUTRIENT_PATH2=NHANES_20172018$NUTRIENT2)
> ```
> 
> Let me know if you have other questions. Glad to help. If you find the dietaryindex package helpful, please consider giving it a Star on GitHub. It helps recognize my work. Also, if you publish the paper, please cite the package as GitHub “dietaryindex”. The package will be written as a paper soon.

After updating the R package, all errors were resolved. Thank you very much for your efforts and contributions. This R package will be referenced in the later article publication.
