### ISSUE TITLE
Hello, it seems that your Dietaryindex package cannot be used with data from the NHANES database for the years 1999-2004, is that correct?

### ISSUE THREAD

**Issue by Fuweixing** [jamesjiadazhan/dietaryindex#215]
How should I calculate the dietary score HEI-2015 for NHANES data from 1999-2004?

**Comment by jamesjiadazhan** [comment]
Thanks for this question. The NHANES 1999-2005 functions are still under development. Once they are finished, they will be published. The next update will happen in the next 1-2 months.

**Comment by Fuweixing** [comment]
> Thanks for this question. The NHANES 1999-2005 functions are still under development. Once they are finished, they will be published. The next update will happen in the next 1-2 months.

Thank you for your response, looking forward to the next update.

**Comment by Fuweixing** [comment]
> Thanks for this question. The NHANES 1999-2005 functions are still under development. Once they are finished, they will be published. The next update will happen in the next 1-2 months.

Are there any alternative methods for calculating HEI-2015 or HEI-2010 scores for NHANES data prior to 2004? I'm concerned that I can't wait for a month.

**Comment by jamesjiadazhan** [comment]
I just added the DII and HEI2015 for 1999-2000 data. The function's name is DII_NHANES_MPED. Good luck.

Let me know if you have other questions. If possible, please give our work a Star on GitHub and cite our work when you publish the work. It helps recognize and appreciate our intellectual efforts and contributions.
<img width="573" alt="image" src="https://github.com/jamesjiadazhan/dietaryindex/assets/108076575/9f7d813f-ed18-4d70-bf27-715a3b58385f">


Jiada James Zhan, Rebecca A Hodge, Anne Dunlop, et al. Dietaryindex: A User-Friendly and Versatile R Package for Standardizing Dietary Pattern Analysis in Epidemiological and Clinical Studies. bioRxiv. Published online August 07, 2023:2023.08.07.548466. doi:10.1101/2023.08.07.548466

**Comment by Fuweixing** [comment]
> I just added the DII and HEI2015 for 1999-2000 data. The function's name is DII_NHANES_MPED. Good luck.
> 
> Let me know if you have other questions. If possible, please give our work a Star on GitHub and cite our work when you publish the work. It helps recognize and appreciate our intellectual efforts and contributions. <img alt="image" width="573" src="https://user-images.githubusercontent.com/108076575/277873149-9f7d813f-ed18-4d70-bf27-715a3b58385f.png">
> 
> Jiada James Zhan, Rebecca A Hodge, Anne Dunlop, et al. Dietaryindex: A User-Friendly and Versatile R Package for Standardizing Dietary Pattern Analysis in Epidemiological and Clinical Studies. bioRxiv. Published online August 07, 2023:2023.08.07.548466. doi:10.1101/2023.08.07.548466

We will. Thanks.
