### ISSUE TITLE
 Whether NHANES_FPED can calculate the data before 2005?

### ISSUE THREAD

**Issue by 94github** [jamesjiadazhan/dietaryindex#237]
Many thanks to the authors for a complete summary of the NHANES Dietary index, which helped me a lot. 

In your introduction to the NHANES_FPED series of functions, you emphasized that it is used after 2005. May I ask what kind of deviation will occur in the results of the data before 2005?

**Comment by jamesjiadazhan** [comment]
It just meant you should use NHANES_MPED functions. If you apply NHANES_FPED functions to NHANES data before 2005, they would not work at all.
