### ISSUE TITLE
对于05年之前的数据，如何计算HEI2015

### ISSUE THREAD

**Issue by love520lfh** [jamesjiadazhan/dietaryindex#250]
### Discussed in https://github.com/jamesjiadazhan/dietaryindex/discussions/249

<div type='discussions-op-text'>

<sup>Originally posted by **love520lfh** February  1, 2024</sup>
05年之前数据计算 HEI2015，能不能提供代码实例</div>

HEI2015_NHANES_MPED(MPED_PER_100_GRAM_PATH = NHANES_19992000$MPED_PER_100_GRAM, WJFRT = NHANES_19992000$WJFRT, NUTRIENT_PATH=NHANES_19992000$NUTRIENT, DEMO_PATH=NHANES_19992000$DEMO)

Error in HEI2015_NHANES_MPED(MPED_PER_100_GRAM_PATH = NHANES_19992000$MPED_PER_100_GRAM,  : 
  object 'COHORT_4' not found

**Comment by jamesjiadazhan** [comment]
You should first download NHANES data before 2005 here: 

- Download the NHANES_combined folder from the Google Drive (https://drive.google.com/drive/u/2/folders/1umjhuS22aHEW_bU5AjYa8vrae91gsb0D)
- Download the NHANES_combined folder from the GitHub dietaryindex_NHANES page (https://github.com/jamesjiadazhan/dietaryindex_NHANES/tree/main/data/NHANES_combined)

Then, use to find the example code
```
?HEI2015_NHANES_MPED
```
