### ISSUE TITLE
Issue with HEI2020

### ISSUE THREAD

**Issue by JulesLarke-USDA** [jamesjiadazhan/dietaryindex#283]
Hello,

I've run into an issue when tryin to use the HEI2020 function. Please see error log below.

Thanks,
Jules

> HEI2020(
   SERV_DATA = nhanes_hei,
   RESPONDENTID = 'SEQN',
   AGE = 'Age',
   TOTALKCAL_HEI2020 = 'kcal',
   TOTALFRT_SERV_HEI2020 = 'total_fruit',
   FRT_SERV_HEI2020 = 'whole_fruit',
   VEG_SERV_HEI2020 = 'total_vegetable',
   GREENNBEAN_SERV_HEI2020 = 'green_and_bean',
   TOTALPRO_SERV_HEI2020 =  'total_protein',
   SEAPLANTPRO_SERV_HEI2020 = 'seafood_plant_protein',
   WHOLEGRAIN_SERV_HEI2020 = 'whole_grain',
   DAIRY_SERV_HEI2020 = 'total_dairy',
   FATTYACID_SERV_HEI2020 = 'fatty_acid_ratio',
   REFINEDGRAIN_SERV_HEI2020 = 'refined_grain',
   SODIUM_SERV_HEI2020 = 'sodium_mg',
   ADDEDSUGAR_SERV_HEI2020 = 'added_sugar',
   SATFAT_SERV_HEI2020 = 'SFA'
 )
Error in `dplyr::mutate()`:
ℹ In argument: `TOTALFRT_SERV_HEI2020 = TOTALFRT_SERV_HEI2020/(TOTALKCAL_HEI2020/1000)`.
Caused by error in `TOTALKCAL_HEI2020 / 1000`:
! non-numeric argument to binary operator
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/dplyr:::mutate_error>
Error in `dplyr::mutate()`:
ℹ In argument: `TOTALFRT_SERV_HEI2020 = TOTALFRT_SERV_HEI2020/(TOTALKCAL_HEI2020/1000)`.
Caused by error in `TOTALKCAL_HEI2020 / 1000`:
! non-numeric argument to binary operator
---
Backtrace:
     ▆
  1. ├─dietaryindex::HEI2020(...)
  2. │ └─... %>% ...
  3. ├─dplyr::mutate(...)
  4. ├─dplyr::mutate(...)
  5. └─dplyr:::mutate.data.frame(...)
  6.   └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
  7.     ├─base::withCallingHandlers(...)
  8.     └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
  9.       └─mask$eval_all_mutate(quo)
 10.         └─dplyr (local) eval()
Run rlang::last_trace(drop = FALSE) to see 3 hidden frames.
> R.Version()
$platform
[1] "aarch64-apple-darwin20"

$arch
[1] "aarch64"

$os
[1] "darwin20"

$system
[1] "aarch64, darwin20"

$status
[1] ""

$major
[1] "4"

$minor
[1] "4.1"

$year
[1] "2024"

$month
[1] "06"

$day
[1] "14"

$`svn rev`
[1] "86737"

$language
[1] "R"

$version.string
[1] "R version 4.4.1 (2024-06-14)"

$nickname
[1] "Race for Your Life"

>

**Comment by jamesjiadazhan** [comment]
Please read the manual carefully before using the function. See the example below:
```
data("HEI2020_VALIDATION")
HEI2020(SERV_DATA = HEI2020_VALIDATION, RESPONDENTID = HEI2020_VALIDATION$id, AGE = HEI2020_VALIDATION$age, TOTALKCAL_HEI2020 = HEI2020_VALIDATION$kcal, TOTALFRT_SERV_HEI2020 = HEI2020_VALIDATION$total_fruit, FRT_SERV_HEI2020 = HEI2020_VALIDATION$whole_fruit, VEG_SERV_HEI2020 = HEI2020_VALIDATION$total_vegetable, GREENNBEAN_SERV_HEI2020 = HEI2020_VALIDATION$green_and_bean, TOTALPRO_SERV_HEI2020 = HEI2020_VALIDATION$total_protein, SEAPLANTPRO_SERV_HEI2020 = HEI2020_VALIDATION$seafood_plant_protein, WHOLEGRAIN_SERV_HEI2020 = HEI2020_VALIDATION$whole_grain, DAIRY_SERV_HEI2020 = HEI2020_VALIDATION$dairy, FATTYACID_SERV_HEI2020 = HEI2020_VALIDATION$fatty_acid, REFINEDGRAIN_SERV_HEI2020 = HEI2020_VALIDATION$refined_grain, SODIUM_SERV_HEI2020 = HEI2020_VALIDATION$sodium, ADDEDSUGAR_SERV_HEI2020 = HEI2020_VALIDATION$added_sugar, SATFAT_SERV_HEI2020 = HEI2020_VALIDATION$saturated_fat)
```
